spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 112296root
    url: jdbc:mysql://localhost:3306/dbtest1
    type: org.apache.tomcat.jdbc.pool.DataSource